language: emacs-lisp
git:
  submodules: false
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq emacs-snapshot emacs-snapshot-el emacs-snapshot-nox
before_script:
  - rm -rf ~/.emacs.d ~/.emacs
  - ln -s $(pwd) ~/.emacs.d
script:
  - emacs --batch --load init.el --kill
