addons:
  apt:
    packages:
      - build-essential
      - libncurses-dev
      - aspell
      - aspell-en
      - fortune
      - cowsay
before_install:
  - wget https://ftp.gnu.org/gnu/emacs/emacs-26.3.tar.xz
  - tar xf emacs-26.3.tar.xz
install:
  - cd emacs-26.3 && ./configure --with-x-toolkit=no --without-all --with-gnutls && make -j
  - ./src/emacs --version
  - cd ..
before_script:
  - rm -rf ~/.emacs.d ~/.emacs
  - ln -s $(pwd) ~/.emacs.d
script:
  - ./emacs-26.3/src/emacs --batch --load ~/.emacs.d/init.el --kill
