sudo: required
dist: trusty
addons:
  apt:
    packages:
      - emacs24-nox
language: generic
git:
  submodules: true
before_script:
  - rm -rf ~/.emacs.d ~/.emacs
  - ln -s $(pwd) ~/.emacs.d
  - emacs --version
script:
  - emacs --batch --load init.el --kill
