language: emacs-lisp
git:
  submodules: false
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq $EMACS
  - if [[ "$EMACS" = 'emacs-snapshot' ]]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-nox;
    fi
before_script:
  - rm -rf ~/.emacs.d ~/.emacs
  - ln -s $(pwd) ~/.emacs.d
script:
  - emacs --batch --load init.el --kill
